---
title: "__ Data Analysis (change title to reflect your study)"
output: html_notebook
---



```{r download packages and format .csv to prepare for analysis}
library(Rmisc)
library(tidyverse)
library(lme4)
library(lmerTest) 
library(jsonlite)
library(car)
library(simr)

path_to_csv = "" #change to match your path


# open .csv and read data
d <- read.csv(path_to_csv)

# eliminate practice trials
d = d[d$trial >= 1, ] 

# assigned name of long format dataframe
dl <- ""
```

### Descriptives
```{r Descriptives of experiment results}

## graph of the distribution of the participants' rankings or results? 

```


### Participant Demographics
```{r Demographics of participants}

## number of participants

## gender

## age

## graph

```


### H1 (Main Effect) Analysis (replace this with description of H1)

#### How does [main effect variable] influence [results]?

```{r H1}

## analysis and p-value of H1

## graph of H1

```


### H2 Analysis (replace this with description of H2)

#### How does [H2 variable] influence [results]?

```{r H2}

## analysis and p-value of H2

## graph of H2

```

### H3 Analysis (replace this with description of H3)

#### How does [H3 variable] influence [results]?

```{r H3}

## analysis and p-value of H3

## graph of H3

```


### Power Analysis 

```{r Power analysis}


set.seed(2532)

PowerModel = "" ##replace with main effect analysis

## use this line to extend the number of trials
PowerModelExt = extend(PowerModel, within = "participant_id+ratingType", n = 50)

## use this line to extend the number of participants
PowerModelExt = extend(PowerModelExt, along = "participant_id", n = 200)

## run sim
powerSim(PowerModelExt, nsim=1000)

# model the curve of this hypothetical experiment
pc <-  powerCurve(PowerModelExt, nsim = 1000, along = "participant_id") 

# plot and numbers
pc 
plot(pc)

```