---
title: "__ Data Analysis (change title to reflect your study)"
output: html_notebook
---

```{r download packages and format csv to prepare for analysis}

library(Rmisc)
library(tidyverse)
library(lme4)
library(lmerTest) 
library(jsonlite)
library(car)
library(simr)
library(knitr)

```


### Descriptives
```{r Descriptives of experiment results}

## graph of the distribution of the participants' rankings or results? 

```


### Participant Demographics
```{r Demographics of participants}

## number of participants

## gender

## age

## graph

```


### H1 (Main Effect) Analysis (replace this with description of H1)

#### How does [main effect variable] influence [results]?

```{r H1}

## analysis and p-value of H1

## graph of H1

```

### Exploratory Analysis (replace this with description)

#### How does [exploratory variable] influence [results]?

```{r Exploratory}

## analysis and p-value

## graph
```



### Power Analysis 

```{r Power analysis}


set.seed(2532)

PowerModel = "" ##replace with main effect analysis

## use this line to extend the number of trials
PowerModelExt = extend(PowerModel, within = "participant_id+ratingType", n = 50)

## use this line to extend the number of participants
PowerModelExt = extend(PowerModelExt, along = "participant_id", n = 200)

## run sim
powerSim(PowerModelExt, nsim=1000)

# model the curve of this hypothetical experiment
pc <-  powerCurve(PowerModelExt, nsim = 1000, along = "participant_id") 

# plot and numbers
pc 
plot(pc)

```